### PR TITLE
Materialize css

### PR DESCRIPTION
**Pull request by ritwickdey**

### CODE REVIEW

**Comment by prithweedas** [comment]
Awesome, let me just try it out once and then I'll merge it

**Comment by prithweedas** [comment]
Issue

[reference](https://github.com/angular/vscode-ng-language-service/issues/149)

**Comment by tejalshroff** [comment]
I am Facing same issue for required and pattern. Please let me know for and alternative which works .

**Comment by prithweedas** [comment]
Unfortunately that issue is still open.
You can check it here https://github.com/angular/vscode-ng-language-service/issues/149

**Pull request merged**
